# configuration for sps
[log_settings]
PtimeLoggingAntenna = 0

[clr_settings]
# delay before clear freq record [seconds]
min_clrfreq_delay = 0.010

# Radar and USRP frequency resolution [Hz]
# (Do NOT use scientific notation)
clrfreq_res = 1000

# Number of spectral averages to perform in CFS
avg_ratio = 4

# trigger new clear freq record if data older than max_age [seconds]
auto_max_age = 30
auto_pause_time = 0.0

[cuda_settings]
MaxChannels = 2
MaxPulses = 8

[shm_settings]
# stoi error on some large values of rxshm_size.., may fail for more than 8 digits?
rxshm_size = 140000000
txshm_size = 15000000

[network_settings]
ServerHost = localhost
CUDADriverPort = 55420
USRPDriverPort = 54420
CUDADriverHostnames_R1 = localhost
CUDADriverHostnames_R2 =
GPSOctoclockHostname =
