# configparser config file describing usrps in the antenna array, for
#   kod as primary and singlePol
# the location of the antenna is not necessarily the antenna number
# TODO: add support for frequency-dependent calibration tables?

# hostname      Hostname of the usrp / driver
# radar         0 for main computer, 1 for remote computer
# mainarray     True for main array, False for back array
# array_idx     Antenna index number (0-15 for main array, 16-19 for back array)
# tdelay        Time delay in seconds
# side          Side of usrp x300
# phase_offset  constant phase offset, useful for controlling polarization or
#                 compensating for 180 phase flip
#
# antenna_idx > 19 will be handled by cuda with modulo 20.
#                 (tx phasing for 2nd polarization)

# local USRPs

[usrp0a]
usrp_hostname = 192.168.50.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 0
tdelay = 0
side = a
phase_offset = 0

[usrp0b]
usrp_hostname = 192.168.50.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 1
tdelay = 0
side = b
phase_offset = 0

[usrp1a]
usrp_hostname = 192.168.51.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 2
tdelay = 0
side = a
phase_offset = 0

[usrp1b]
usrp_hostname = 192.168.51.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 3
tdelay = 0
side = b
phase_offset = 0

[usrp2a]
usrp_hostname = 192.168.52.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 4
tdelay = 0
side = a
phase_offset = 0

[usrp2b]
usrp_hostname = 192.168.52.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 5
tdelay = 0
side = b
phase_offset = 0

[usrp3a]
usrp_hostname = 192.168.53.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 6
tdelay = 0
side = a
phase_offset = 0

[usrp3b]
usrp_hostname = 192.168.53.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 7
tdelay = 0
side = b
phase_offset = 0

[usrp4a]
usrp_hostname = 192.168.54.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 8
tdelay = 0
side = a
phase_offset = 0

[usrp4b]
usrp_hostname = 192.168.54.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 9
tdelay = 0
side = b
phase_offset = 0

[usrp5a]
usrp_hostname = 192.168.55.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 10
tdelay = 0
side = a
phase_offset = 0

[usrp5b]
usrp_hostname = 192.168.55.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 11
tdelay = 0
side = b
phase_offset = 0

[usrp6a]
usrp_hostname = 192.168.56.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 12
tdelay = 0
side = a
phase_offset = 0

[usrp6b]
usrp_hostname = 192.168.56.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 13
tdelay = 0
side = b
phase_offset = 0

[usrp7a]
usrp_hostname = 192.168.57.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 14
tdelay = 0
side = a
phase_offset = 0

[usrp7b]
usrp_hostname = 192.168.57.2
driver_hostname = localhost
radar = 0
mainarray = True
array_idx = 15
tdelay = 0
side = b
phase_offset = 0

[usrp8a]
usrp_hostname = 192.168.58.2
driver_hostname = localhost
radar = 0
mainarray = False
array_idx = 16
tdelay = 0
side = a
phase_offset = 0

[usrp8b]
usrp_hostname = 192.168.58.2
driver_hostname = localhost
radar = 0
mainarray = False
array_idx = 17
tdelay = 0
side = b
phase_offset = 0

[usrp9a]
usrp_hostname = 192.168.59.2
driver_hostname = localhost
radar = 0
mainarray = False
array_idx = 18
tdelay = 0
side = a
phase_offset = 0

[usrp9b]
usrp_hostname = 192.168.59.2
driver_hostname = localhost
radar = 0
mainarray = False
array_idx = 19
tdelay = 0
side = b
phase_offset = 0
